### ISSUE TITLE
ModuleNotFoundError after build and run

### ISSUE THREAD

**Issue by pexa-araza** [aws/aws-graviton-getting-started#265]
porting-advisor-for-graviton/dist [main] $ ./porting-advisor-macosx-arm64 ~/projects/pexa_app
Traceback (most recent call last):
  File "porting-advisor.py", line 23, in <module>
  File "advisor/__init__.py", line 26, in main
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "advisor/main.py", line 28, in <module>
ModuleNotFoundError: No module named 'advisor.reports.report_factory'
[90036] Failed to execute script 'porting-advisor' due to unhandled exception!
araza porting-advisor-for-graviton/dist [main] $

**Comment by AWSjswinney** [comment]
This issue really belongs on the [Porting Advisor for Graviton](https://github.com/aws/porting-advisor-for-graviton) repository. Is this a problem you still see on the latest version of that?

**Comment by jamolina** [comment]
@pexa-araza like @AWSjswinney mentioned, could you try to pull the latest changes? Also, could you tell us which version of Python are you using?

**Comment by AWSjswinney** [comment]
Let us know if you still need help!
