### ISSUE TITLE
Compilation of Pytorch fails

### ISSUE THREAD

**Issue by zheng-da** [aws/aws-graviton-getting-started#46]
I'm following the instruction in this [Python doc](https://github.com/aws/aws-graviton-getting-started/blob/master/python.md), but fail with the following error:
```
/home/ubuntu/pytorch/aten/src/ATen/cpu/vec256/missing_vst1_neon.h:5:1: error: redefinition of ‘void vst1q_f32_x2(float32_t*, float32x4x2_t)’
    5 | vst1q_f32_x2 (float32_t * __a, float32x4x2_t val)
      | ^~~~~~~~~~~~
In file included from /home/ubuntu/pytorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/ubuntu/pytorch/aten/src/ATen/cpu/FlushDenormal.cpp:3:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:28197:1: note: ‘void vst1q_f32_x2(float32_t*, float32x4x2_t)’ previously defined here
28197 | vst1q_f32_x2 (float32_t * __a, float32x4x2_t val)
      | ^~~~~~~~~~~~
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/build.make:636: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/FlushDenormal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:8902: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I'm compiling Pytorch on ubuntu 20.04 and the compiler is gcc 9.3.0.

It seems Pytorch changed recently. `aten/src/ATen/cpu/vec256/missing_vst1_neon.h` is added to Pytorch very recently. Could you provide clear instructions on compiling Pytorch?

**Comment by AWSNB** [comment]
Thanks for raising this Da Zheng

Could be related to a recently introduce patch to fix gcc7 issue.   Will update u soon

Sent from my iPhone

On Sep 11, 2020, at 7:37 PM, Da Zheng <notifications@github.com> wrote:

﻿

I'm following the instruction in this Python doc<https://github.com/aws/aws-graviton-getting-started/blob/master/python.md>, but fail with the following error:

/home/ubuntu/pytorch/aten/src/ATen/cpu/vec256/missing_vst1_neon.h:5:1: error: redefinition of ‘void vst1q_f32_x2(float32_t*, float32x4x2_t)’
    5 | vst1q_f32_x2 (float32_t * __a, float32x4x2_t val)
      | ^~~~~~~~~~~~
In file included from /home/ubuntu/pytorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/ubuntu/pytorch/aten/src/ATen/cpu/FlushDenormal.cpp:3:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:28197:1: note: ‘void vst1q_f32_x2(float32_t*, float32x4x2_t)’ previously defined here
28197 | vst1q_f32_x2 (float32_t * __a, float32x4x2_t val)
      | ^~~~~~~~~~~~
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/build.make:636: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/FlushDenormal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:8902: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2


I'm compiling Pytorch on ubuntu 20.04 and the compiler is gcc 9.3.0.

It seems Pytorch changed recently. aten/src/ATen/cpu/vec256/missing_vst1_neon.h is added to Pytorch very recently. Could you provide clear instructions on compiling Pytorch?

**Comment by zheng-da** [comment]
I checked out its branch of 1.6. it works now

**Comment by jasonrandrews** [comment]
Glad it's working now. There is a [PyTorch 1.6 build recipe with gcc9](https://github.com/ARM-software/Tool-Solutions/tree/master/docker/pytorch-aarch64) that may be useful.

**Comment by AWSNB** [comment]
@zheng-da we reproduced the problem on both ubuntu 18 and 20,   seems some of latest commits to pytorch master branch broke this,  @sebpop  is debugging and will submit a fix

**Comment by sebpop** [comment]
https://github.com/pytorch/pytorch/pull/44644 fixed the problem.

**Comment by tarunallyo** [comment]
While compiling the Pytorch it ended with this

```
Copying torch.egg-info to /usr/local/lib/python3.8/dist-packages/torch-1.7.0a0+f02753f.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /usr/local/bin
Installing convert-onnx-to-caffe2 script to /usr/local/bin
root@844a887ed7ed:/pytorch# -- MKL library not found
bash: --: command not found
root@844a887ed7ed:/pytorch# -- MKL library not found
bash: --: command not found
```
I also tried to install the ``` MKL ``` but it says architecture is not supported.
Do we have any document for the same or could you provide instructions for the same ?

**Comment by AWSNB** [comment]
@tarunallyo  MKL is intel specific math libraries that would not work here

i'm curious how you trying to build/install ?    we've just updated the [Pytorch installation](https://github.com/aws/aws-graviton-getting-started/blob/master/python.md)

the normal installation should recognize this is not Intel and would not include the MKL package
alternatively, u can make sure MKL is not included using:
export USE_MKL=0
export USE_MKLDNN=0

**Comment by tarunallyo** [comment]
I have used 
![image](https://user-images.githubusercontent.com/61626340/93302673-ffeed580-f817-11ea-9eaa-0a8091789a73.png)
which was in the previous version of doc [Pytorch Intsallation](https://github.com/aws/aws-graviton-getting-started/blob/master/python.md). Still got that error.

**Comment by AWSNB** [comment]
@tarunallyo  may I ask what Linux distribution are you using ?

the older version of pytorch installation guide missed defining some dependencies, which caused pytorch compilation to fail on latest source code, we've seen similar issue (not exactly MKL), that went away with the new instructions

please let us know if the new instructions work (pls note the prerequisite portion)

**Comment by tarunallyo** [comment]
Cool, that's working now.  Thanks for the new steps.

**Comment by tarunallyo** [comment]
@AWSNB @zheng-da Looks like pytorch version 1.6 is not getting installed. 1.8 works. 

```
[ 60%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/IndexingUtils.cpp.o
    [ 60%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Integration.cpp.o
    In file included from /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256.h:10:0,
                     from /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/functional.h:6,
                     from /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vml.h:5,
                     from /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/native/GridSampler.cpp:7:
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:262:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
       const float operator[](int idx) const {
       ^~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:267:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
       const float operator[](int idx) {
       ^~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In static member function 'static at::vec256::{anonymous}::Vec256<float> at::vec256::{anonymous}::Vec256<float>::loadu(const void*, int64_t)':
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:213:14: error: 'vld1q_f32_x2' was not declared in this scope
           return vld1q_f32_x2(reinterpret_cast<const float*>(ptr));
                  ^~~~~~~~~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:213:14: note: suggested alternative: 'vld1q_f32'
           return vld1q_f32_x2(reinterpret_cast<const float*>(ptr));
                  ^~~~~~~~~~~~
                  vld1q_f32
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:230:14: error: 'vld1q_f32_x2' was not declared in this scope
           return vld1q_f32_x2(reinterpret_cast<const float*>(tmp_values));
                  ^~~~~~~~~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:230:14: note: suggested alternative: 'vld1q_f32'
           return vld1q_f32_x2(reinterpret_cast<const float*>(tmp_values));
                  ^~~~~~~~~~~~
                  vld1q_f32
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In member function 'void at::vec256::{anonymous}::Vec256<float>::store(void*, int64_t) const':
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: error: 'vst1q_f32_x2' was not declared in this scope
           vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
           ^~~~~~~~~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: note: suggested alternative: 'vst1q_f32'
           vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
           ^~~~~~~~~~~~
           vst1q_f32
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: error: 'vst1q_f32_x2' was not declared in this scope
           vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
           ^~~~~~~~~~~~
    /tmp/pip-req-build-1n4zgkp8/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: note: suggested alternative: 'vst1q_f32'
           vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
           ^~~~~~~~~~~~
           vst1q_f32
    caffe2/CMakeFiles/torch_cpu.dir/build.make:2869: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o' failed
    make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:8167: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
    make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-1n4zgkp8/setup.py", line 737, in <module>
        build_deps()
      File "/tmp/pip-req-build-1n4zgkp8/setup.py", line 321, in build_deps
        cmake=cmake)
      File "/tmp/pip-req-build-1n4zgkp8/tools/build_pytorch_libs.py", line 62, in build_caffe2
        cmake.build(my_env)
      File "/tmp/pip-req-build-1n4zgkp8/tools/setup_helpers/cmake.py", line 345, in build
        self.run(build_args, my_env)
      File "/tmp/pip-req-build-1n4zgkp8/tools/setup_helpers/cmake.py", line 141, in run
        check_call(command, cwd=self.build_dir, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1n4zgkp8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1n4zgkp8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z4yu4cth/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/torch Check the logs for full command output.
```
