### ISSUE TITLE
jamspell not getting installed on arm c6

### ISSUE THREAD

**Issue by tarunallyo** [aws/aws-graviton-getting-started#52]
Here are the logs:

```
pip3 install jamspell
Collecting jamspell
  Using cached jamspell-0.0.11.tar.gz (60 kB)
Building wheels for collected packages: jamspell
  Building wheel for jamspell (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-chqx4k0p
       cwd: /tmp/pip-install-hdkdegey/jamspell/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 51, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 33, in run
      self.run_command('build_ext')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 506, in build_extension
      sources = self.swig_sources(sources, ext)
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 597, in swig_sources
      swig = self.swig or self.find_swig()
    File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 46, in find_swig
      assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
    Running setup.py install for jamspell ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o98yr49h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/jamspell
         cwd: /tmp/pip-install-hdkdegey/jamspell/
    Complete output (34 lines):
    running install
    running build_ext
    building '_jamspell' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 51, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 39, in run
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 506, in build_extension
        sources = self.swig_sources(sources, ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 597, in swig_sources
        swig = self.swig or self.find_swig()
      File "/tmp/pip-install-hdkdegey/jamspell/setup.py", line 46, in find_swig
        assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
    AssertionError
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hdkdegey/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o98yr49h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/jamspell Check the logs for full command output.
```

**Comment by tarunallyo** [comment]
Just in case, if someone faces it , the steps mentioned here fixed the issue. Before jamspell, swig version 3 was required.

Install swig from here:
https://www.dev2qa.com/how-to-install-swig-on-macos-linux-and-windows/

Then run
```
pip3 install jamspell
```

It worked. closing this thread now.
